# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "kubedrop.io/drupal-node"
version = "0.0.1"
name = "Drupal Node Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.kubedrop.drupal-node"